<a href="https://colab.research.google.com/github/Encarnacion-Angel/Encarnacion-Angel/blob/main/HOA6_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hands-on Activity 6.2 Getting Started with Pandas

Angel Encarnacion

Miguel G. Pabilan

# Exercises
4. Output

In [ ]:
# Exercise 1.1 Create a DataFrame by reading in the 2019_Yellow_Taxi_Trip_Data.csv file. Examine the first 5 rows.
from google.colab import files

uploaded = files.upload()

In [ ]:
import pandas as pd
df = pd.read_csv("2019_Yellow_Taxi_Trip_Data.csv")
df.head(5)

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2,2019-10-23T16:39:42.000,2019-10-23T17:14:10.000,1,7.93,1,N,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5
1,1,2019-10-23T16:32:08.000,2019-10-23T16:45:26.000,1,2.00,1,N,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0
2,2,2019-10-23T16:08:44.000,2019-10-23T16:21:11.000,1,1.36,1,N,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5
3,2,2019-10-23T16:22:44.000,2019-10-23T16:43:26.000,1,1.00,1,N,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5
4,2,2019-10-23T16:45:11.000,2019-10-23T16:58:49.000,1,1.96,1,N,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5

In [ ]:
# Exercise 1.2 Find the dimensions (number of rows and number of columns) in the data.
df.shape

(10000, 18)

In [ ]:
df.columns

Index(['vendorid', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'ratecodeid', 'store_and_fwd_flag',
       'pulocationid', 'dolocationid', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge'],
      dtype='object')

In [ ]:
df.dtypes

vendorid                   int64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count            int64
trip_distance            float64
ratecodeid                 int64
store_and_fwd_flag        object
pulocationid               int64
dolocationid               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [ ]:
df.head()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2,2019-10-23T16:39:42.000,2019-10-23T17:14:10.000,1,7.93,1,N,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5
1,1,2019-10-23T16:32:08.000,2019-10-23T16:45:26.000,1,2.00,1,N,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0
2,2,2019-10-23T16:08:44.000,2019-10-23T16:21:11.000,1,1.36,1,N,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5
3,2,2019-10-23T16:22:44.000,2019-10-23T16:43:26.000,1,1.00,1,N,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5
4,2,2019-10-23T16:45:11.000,2019-10-23T16:58:49.000,1,1.96,1,N,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5

In [ ]:
df.tail()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
9995,1,2019-10-23T17:39:59.000,2019-10-23T17:49:26.000,2,1.3,1,N,238,239,1,8.0,3.5,0.5,2.46,0.0,0.3,14.76,2.5
9996,1,2019-10-23T17:53:02.000,2019-10-23T18:00:45.000,1,1.4,1,N,239,166,2,8.0,3.5,0.5,0.00,0.0,0.3,12.30,2.5
9997,1,2019-10-23T17:07:16.000,2019-10-23T17:11:35.000,1,0.7,1,N,166,152,2,5.0,1.0,0.5,0.00,0.0,0.3,6.80,0.0
9998,1,2019-10-23T17:38:26.000,2019-10-23T17:49:28.000,2,2.5,1,N,151,42,1,10.0,1.0,0.5,0.00,0.0,0.3,11.80,0.0
9999,1,2019-10-23T17:22:14.000,2019-10-23T17:52:09.000,1,3.0,1,N,237,68,1,19.0,3.5,0.5,2.50,0.0,0.3,25.80,2.5

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   vendorid               10000 non-null  int64
 1   tpep_pickup_datetime   10000 non-null  object
 2   tpep_dropoff_datetime  10000 non-null  object
 3   passenger_count        10000 non-null  int64
 4   trip_distance          10000 non-null  float64
 5   ratecodeid             10000 non-null  int64
 6   store_and_fwd_flag     10000 non-null  object
 7   pulocationid           10000 non-null  int64
 8   dolocationid           10000 non-null  int64
 9   payment_type           10000 non-null  int64
 10  fare_amount            10000 non-null  float64
 11  extra                  10000 non-null  float64
 12  mta_tax                10000 non-null  float64
 13  tip_amount             10000 non-null  float64
 14  tolls_amount           10000 non-null  float64
 15  improvement_surcharge  10000 non-null  float64
 16  total_amount           10000 non-null  float64
 17  congestion_surcharge   10000 non-null  float64
dtypes: float64(9), int64(6), object(3)
memory usage: 1.4+ MB

In [ ]:
# Exercise 1.3 Using the data in the 2019_Yellow_Taxi_Trip_Data.csv file, calculate summary statistics for the fare_amount, tip_amount, tolls_amount, and total_amount columns.

In [ ]:
df.fare_amount.value_counts()

fare_amount
52.00    447
6.50     442
6.00     438
7.50     423
7.00     419
        ...
93.00      1
17.46      1
96.00      1
89.00      1
62.50      1
Name: count, Length: 199, dtype: int64

In [ ]:
df.tip_amount.value_counts()

tip_amount
0.00     3143
1.00      497
2.00      386
2.06      126
2.36      119
         ...
7.33        1
37.25       1
3.11        1
7.76        1
17.75       1
Name: count, Length: 657, dtype: int64

In [ ]:
df.tolls_amount.value_counts()

tolls_amount
 0.00      9164
 6.12       764
 12.50       16
 17.50        6
 5.76         6
 18.50        4
 2.80         4
 20.00        3
 18.00        2
 10.62        2
 18.62        2
 15.25        2
 19.75        1
 15.50        1
 612.00       1
 14.70        1
 14.65        1
 6.14         1
 10.00        1
 12.54        1
 13.90        1
 2.29         1
 25.00        1
 21.00        1
 18.70        1
 8.12         1
 17.90        1
 14.95        1
 15.00        1
 8.62         1
-6.12         1
 12.24        1
 18.60        1
 21.12        1
 9.50         1
 15.95        1
 27.00        1
Name: count, dtype: int64

In [ ]:
df.total_amount.value_counts()

total_amount
11.80     181
12.30     175
10.80     173
13.30     166
10.30     164
         ...
106.55      1
131.80      1
16.05       1
66.85       1
75.00       1
Name: count, Length: 1097, dtype: int64

In [ ]:
# Exercise 1.4 Isolate the fare_amount, tip_amount, tolls_amount, and total_amount for the longest trip by distance (trip_distance).

In [ ]:
longest_trip = df.loc[df['trip_distance'].idxmax(), ['fare_amount', 'tip_amount', 'tolls_amount', 'total_amount']]
longest_trip

fare_amount      176.0
tip_amount       18.29
tolls_amount      6.12
total_amount    201.21
Name: 8338, dtype: object

# Chosen Dataset: Iris

5. Supplementary Activity

In [ ]:
# Exercise 1.1 Create a DataFrame by reading in the Iris.csv file. Examine the first 5 rows.

In [ ]:
import pandas as pd

iris = pd.read_csv('/content/Iris.csv')
iris.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
# Exercise 1.2 Find the dimensions (number of rows and number of columns) in the data.

In [ ]:
iris.shape

(150, 6)

In [ ]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
iris.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
# Exercise 1.3 Using the data in the Iris.csv file, calculate summary statistics for the Sepal Length, Sepal Width, Petal Length, Petal Width, and Species.

In [ ]:
summary_statistics = iris.describe()
iris["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
# Exercise 1.4 Isolate the Sepal Length, Sepal Width, Petal Length, Petal Width and the Species

In [ ]:
iris_selected = iris[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm", "Species"]]
iris_selected

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]